# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: turtle programmer
email: manas@fuzzysparkle.com
description: > # this means to ignore newlines until "baseurl:"
    Because being a programmer is like being a turtle.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.turtleprogrammer.com" # the base hostname & protocol for your site

# Build settings
#markdown: redcarpet
#highlighter: pygments
# redcarpet:
#   extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
